import { Open_Sans, Anton } from "next/font/google";
import "./globals.css";
//Components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import SlideFadeTransition from "@/components/SlideFadeTransition";

const sans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sans",
});

const anton = Anton({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-anton",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${(sans.variable, anton.variable)} `}>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
